<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
?>
<?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();?>
<span data-action="toggle-nav" class="action nav-toggle"><span><?php /* @escapeNotVerified */ echo __('Toggle Nav') ?></span></span>
<?php if ($block->isHomePage()):?>
    <strong class="logo">
<?php else: ?>
    <a class="logo" href="<?php echo $block->getUrl(''); ?>" title="<?php /* @escapeNotVerified */ echo $storeName ?>">
<?php endif ?>
        <img class="main-logo" src="<?php /* @escapeNotVerified */ echo $block->getLogoSrc() ?>"
             alt="<?php /* @escapeNotVerified */ echo $block->getLogoAlt() ?>"
             <?php echo $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?>
             <?php echo $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?>
        />
        <?php 	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
				$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
				?>
		<img class="mobile-logo" src="<?php echo $storeManager->getStore()->getBaseUrl() ?>pub/media/logo/default/mobile-logo.png" alt="mobile-logo"/>
<?php if ($block->isHomePage()):?>
    </strong>
<?php else:?>
    </a>
<?php endif?>
<script type="text/javascript">
require(["jquery"], function($){
    $(document).ready(function(){
		if($(window).width() > 767){
		$(".filter-options-title").addClass('sign');		
		$(".filter-options-title").click(function(){
			$(".filter-options-title").removeClass('togle-sidenav');
			$(this).toggleClass('sign');			
			$(this).addClass('togle-sidenav');		
			$('.togle-sidenav').next().slideToggle();
			
		});
		}
		else{
		$(".filter-options-content").hide();			
		$(".filter-options-title").click(function(){
			$(".filter-options-title").removeClass('togle-sidenav');
			$(this).toggleClass('sign');			
			$(this).addClass('togle-sidenav');		
			$('.togle-sidenav').next().slideToggle();
			
		});
		}
		
	});
	 $(document).ready(function() {
		var showChar = 200;
	
		var moretext = "More";
		var lesstext = "Less";
		$('.category-description p').each(function() {
			var content = $(this).html();

			   if(content.length > showChar) {
	 
				var c = content.substr(0, showChar);
				var h = content.substr(showChar-0, content.length - showChar);
	 
				var html = c + '<span class="moreellipses"></span><span class="morecontent"><span style="display:none;">' + h + '</span>  <a href="" class="morelink">' + moretext + '</a></span>';
	 
				$(this).html(html);
			}
	 
		})

		$(".morelink").click(function(){
			if($(this).hasClass("less")) {
				$(this).removeClass("less");
				$(this).html(moretext);
			} else {
				$(this).addClass("less");
				$(this).html(lesstext);
			}
			$(this).parent().prev().toggle();
			$(this).prev().toggle();
			return false;
		});
		// popup inner border
		$('.freeship').click(function(){	
			setTimeout(function(){
				$('.modal-inner-wrap').wrapInner('<div class="freeshipping-inner"></div>');
			},100);
		});
		
});
	$(window).on('load resize', function(){
		if($(window).width() < 768){
			if($('.home-video-section .whoweare').length == 0){
					$('.home-video-section').append('<div class="whoweare">Who We Are <span>+<span></div>');
				}
			$('.whoweare').insertBefore('.home-video-section .home-video-content');
			
			
			$('.whoweare').click(function(){
				$(this).toggleClass('ico-tg');
				$('.home-video-content').slideToggle('slow');
				exit(0);
			});
			$('.nav-toggle').insertAfter('.logo');
			$('.cart-summary').insertAfter('.form.form-cart')
			$('.header.content .block-search .label').click(function(){
				$('#maincontent').toggleClass('search-op');
			});
			$('.product.data.items *').off();
			$('.data.item.content').hide();
			setTimeout(function(){
			$('.data.item.title').each(function(){
				$(this).removeClass('active');
			});
			}, 500);
			$('div.title').on('click', function(e){
					e.preventDefault();
					$(this).toggleClass('active');
					$(this).next('div.content').slideToggle('slow');
					exit(0);
				} );
					setTimeout(function(){
					var titlenew = $('.page-title-wrapper.product').html();
					
							$(titlenew).insertBefore('.column.main');
							$('.page-title-wrapper.product').remove();
					},20);
						
						
		}
			else{
					
				$('.whoweare').remove();
			}
			var f_wid = ($(window).width() - $('#maincontent').width()) / 2;
			$('#scrolltotop').css('right', f_wid-62 + 'px');
			$('.page-title-wrapper.product').insertBefore('.product-info-sub');
			
			
	});
});

</script>