<style>
    .s_description{
        width:100%;
        height:auto;
        text-align: justify;
    }
    .s_description img{
        max-width:100%;
    }
    .short_des{
        clear: both;
    }
    .box1{
        -o-text-overflow: ellipsis;   /* Opera */
        text-overflow:    ellipsis;   /* IE, Safari (WebKit) */
        overflow:hidden;              /* don't show excess chars */
        white-space:nowrap;           /* force single line */
        width: 100%;
    }
	
	.short_des .box1 span.by_brand {
    border-bottom: solid #4d4d4f 1px;
    padding-bottom: 3px; display:inline-block;
}
.short_des .box1 span.by_brand:hover {
    border-bottom: solid #FD570C 1px; color:#FD570C;
}
.home-content-banner ul li a{height: 38px; line-height: 38px; border: 1px solid #333;}
</style>
<?php
$brand = $this->getBrand();
if($brand):
    if($brand->getId()):
        ?>
        <div class="short_des">
            <a href="<?php echo $this->getUrl($brand->getUrlKey());?>">
                <?php
                /* if($brand->getLogo())
                {
                    $img = $this->getObjectManager()->get('Magestore\Shopbybrand\Helper\Image')
                        ->getMediaUrlImage($brand->getLogo());
                    ?>
                    <img style="width: 13%;" src="<?php echo $img;?>" title="<?php echo $brand->getBrandName();?>"/>
                    <?php
                } */
                ?>
                <div class="box1">
                    <span class="by"><?php echo 'by '; ?></span> <span class="by_brand"><?php echo $brand->getBrandName();?></span>
                </div>
            </a>
        </div>
    <?php endif; endif; ?>
