<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
?>
<?php 
	$object =  \Magento\Framework\App\ObjectManager::getInstance();
	$cart = $object->create('Magento\Checkout\Model\Cart')->getQuote()->getAllVisibleItems();
	$cartCount = count( $cart );
?>
<div data-block="minicart" class="minicart-wrapper">
    <a class="action showcart" href="<?php /* @escapeNotVerified */ echo $block->getShoppingCartUrl(); ?>"
       data-bind="scope: 'minicart_content'">
        <span class="text"><?php /* @escapeNotVerified */ echo __('My Cart'); ?></span>
		<span class="counter qty empty"
              data-bind="css: { empty: cart().summary_count == 0 }, blockLoader: isLoading">
            <span class="counter-number">
			<!-- ko ifnot: cart().summary_count -->
			<!-- ko text: 0 --><!-- /ko -->
			<!-- /ko -->
			<!-- ko if : cart().summary_count > 0 -->
			<!-- ko text: cart().summary_count --><!-- /ko -->
			<!-- /ko -->
			</span>
            
            <span class="counter-label">
            <!-- ko if: cart().summary_count -->
                <!-- ko text: cart().summary_count --><!-- /ko -->
                <!-- ko i18n: 'items' --><!-- /ko -->
            <!-- /ko -->
            </span>
        </span>
    </a>
    <?php if ($block->getIsNeedToDisplaySideBar()): ?>
        <div class="block block-minicart empty"
             data-role="dropdownDialog"
             data-mage-init='{"dropdownDialog":{
                "appendTo":"[data-block=minicart]",
                "triggerTarget":".showcart",
                "timeout": "2000",
                "closeOnMouseLeave": false,
                "closeOnEscape": true,
                "triggerClass":"active",
                "parentClass":"active",
                "buttons":[]}}'>
            <div id="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>
        </div>
    <?php endif ?>
    <script>
        window.checkout = <?php /* @escapeNotVerified */ echo \Zend_Json::encode($block->getConfig()); ?>;
    </script>
    <script type="text/x-magento-init">
    {
        "[data-block='minicart']": {
            "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
        }
    }
    </script>
</div>
<!--<style>
	
	body._has-modal-custom .modal-custom-overlay { display: none !important;}
</style>-->


<script>
/* require(['jquery', 'jquery/ui'], function($){ 
	$(document).ready(function () {
		$(".action.showcart").hover(function(){
		$(".action.showcart").addClass('active');	
		$(".minicart-wrapper").addClass('active');	
		$('.mage-dropdown-dialog').show();
			},function(){
				$(".action.showcart").removeClass('active');	
				$(".minicart-wrapper").removeClass('active');	
				$('.mage-dropdown-dialog').hide();
			});
			
	});
});
 */
</script>








