<?php
$categories = $this->getStoreCategories(true,false,true);
$categoryHelper = $this->getCategoryHelper();

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$mediaurl =$storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
?>

<ul class="main-cat">


<?php
foreach($categories as $category):
		
     if (!$category->getIsActive()) {
        continue;
     }
?>
<li>
	<a href="<?php echo $categoryHelper->getCategoryUrl($category) ?>">
	  <span class="cat-thumb-img">
	  
	  <?php $categoryobj = $objectManager->create('Magento\Catalog\Model\CategoryFactory');
			$_category = $categoryobj->create()->load($category->getEntityId()); ?>
	<?php if($_imgUrl = $_category->getData('thumbnail_image')){?>
	  <img src="<?php echo  $mediaurl.'catalog/category/'.$_imgUrl ; ?>" alt="<?php echo $category->getName() ?>" width="189" height="189" >
		<?php } else{ ?>
		<img src="<?php echo $this->getViewFileUrl('images/cat-placeholder.jpg'); ?>" alt="<?php echo $category->getName() ?>" width="189" height="189" >
		<?php } ?>
		</span>
		<span class="cat-name"><?php echo $category->getName() ?></span>
	</a>
</li>

<?php  

endforeach;
?>
</ul>

