<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$request = $objectManager->get('Magento\Framework\App\Action\Context')->getRequest(); 

?>

<div class="footer-design">
<?php if ($request->getFullActionName() == 'cms_index_index'){ ?>

<img src="<?php echo $this->getViewFileUrl('images/footer-home-logo.jpg'); ?>" alt="home footer logo">

<?php  }
	else{ 
			?>
<img src="<?php echo $this->getViewFileUrl('images/footer-logo-inner.jpg'); ?>" alt="inner footer logo">
	
<?php 	}	?>

</div>



<div id="popup-mpdal" class="popup-mpdal">

<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('freeshiping')->toHtml();?>

</div> 


<?php 
//------------remove slash from urldecode 
$urlInterface = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Framework\UrlInterface');
$current_url = $urlInterface->getCurrentUrl(); 

$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$home = $storeManager->getStore()->getBaseUrl();
 

if(substr($current_url , -1)=='/' && $home != $current_url){
 
	$url = rtrim($current_url, '/');
	header('Location:'.$url);
	exit(); 
	 
}
?>


