<?php
//echo 'test';
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$_product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');//get current product ?>
	<?php 
	$regPrice = number_format($_product->getPrice(),'2', '.', ',');
	$spePrice = number_format($_product->getFinalPrice(), '2', '.', ',');
	$currntDate = date('Y-m-d');
	$spclToDate = substr($_product->getSpecialToDate(),0,10);
	$newFromDate = substr($_product->getNewsFromDate(),0,10);				
	
	if(strtotime($spclToDate) >= strtotime($currntDate) && $spePrice < $regPrice){ ?>
	
	<span class="label "><img src="<?php echo $this->getViewFileUrl('images/sale.png'); ?>"></span>
	<?php } 
	if($newFromDate >= $currntDate){ ?>
	<span class="label "><img src="<?php echo $this->getViewFileUrl('images/new.png'); ?>"></span>
	<?php } ?>